### ISSUE TITLE
TweetDeck

### ISSUE THREAD

**Issue by DanaMW** [scambier/userscripts#1]
Hello and thanks for the script. Would it be possible for you to add the feature set to tweetdeck.twitter.com? Thanks.

**Comment by scambier** [comment]
Fixed with release 0.4, but partially.

- Gif in timeline: ok
- Video in timeline: ok
- Gif in single tweet: ok
- Video in single tweet: not ok

Twitter does a lot of weird stuff with the location object, and Tweetdeck is even worse: for some reason, when accessible a single tweet with a video (not gif), the location is reported as "twitter.com" (not tweetdeck), and the script takes the wrong path. I tried different workarounds to no avail.

![2019-05-09 22_28_49-TweetDeck - Brave](https://user-images.githubusercontent.com/3216752/57485052-03309380-72ab-11e9-8ee7-639a4ba52e42.png)
